-- A dispute on a transaction, a transaction can only have one current
-- dispute which represent either an active (status = 'Submitted')
-- or the most recent closed dispute (status = 'Accepted' / 'Rejected')
CREATE TABLE dispute (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- ID of the transaction, not a foreign key as it references a remote entity
    transaction_id TEXT NOT NULL,

    -- Reason for the dispute supplied by the Purchaser
    reason TEXT NOT NULL,

    -- Boolean flag that is set to TRUE if this row represent the
    -- current active or most recent dispute for the transacton.
    is_current BOOLEAN NOT NULL DEFAULT TRUE
);

-- Log of status changes for a dispute
CREATE TABLE dispute_status_log (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	dispute_id BIGINT NOT NULL REFERENCES dispute (id),

    status TEXT NOT NULL CHECK (
        status IN (
            'Submitted', -- Initial status, submitted by Purchaser
            'Accepted',  -- Positive outcome, accepted by Admin
            'Rejected'   -- Negative outcome, rejected by Admin
        )
    ),

    -- User that performed the action and the time of the
    -- action that resulted in the status for the dispute.
    user_id TEXT NOT NULL,
    time TIMESTAMPTZ DEFAULT NOW(),

    -- Boolean flag that is set to TRUE if this row
    -- represent the current status of the dispute.
    is_current BOOLEAN NOT NULL DEFAULT TRUE
);

-- Index to ensure a maximum of one current dispute per transaction
CREATE UNIQUE INDEX dispute_is_current_index
ON dispute (transaction_id, is_current)
WHERE is_current = TRUE;

-- Index to ensure a maximum one dispute status log entry which is current
CREATE UNIQUE INDEX dispute_status_log_is_current_index
ON dispute_status_log (dispute_id, is_current)
WHERE is_current = TRUE;

